### ISSUE TITLE
DWI B0 and mask

### ISSUE THREAD

**Issue by njhunsak** [kaitlyngreer/psych516w2020#4]
1. Your walltime needs to be 15 minutes

https://github.com/kaitlyngreer/psych516w2020/blob/f3a1fcfbea07af990e30ca1c5d7d561554cba314/Week%206%20Assignments/WK6_b0-job.sh#L3

2. You need to include FSL in your environmental variables

3. You have a complete mess with your directories:

BIDS location: `~/compute/psych516/Data/BIDS/EDSD/`
pT1 location: `~/compute/psych516/Data/derivative/EDSD/pT1/${SUBJID}/`
pDWI location: `~/compute/psych516/Data/BIDS/EDSD/${SUBJID}/derivative`
Current working directory for job script: `~/compute/psych516/Data/BIDS/EDSD/${SUBJID}/dwi`

Your pDWI location needs to be: `~/compute/psych516/Data/derivative/EDSD/pDWI/`
Your actual working directory needs to be: `~/compute/psych516/Data/derivative/EDSD/pDWI/${SUBJID}`
Your symlinks will then need to include fullpath to your BIDS dwi files and create links in your pDWI derivative folder.

https://github.com/kaitlyngreer/psych516w2020/blob/f3a1fcfbea07af990e30ca1c5d7d561554cba314/Week%206%20Assignments/WK6_b0-job.sh#L14-L16

**Comment by kaitlyngreer** [comment]
I've uploaded a new script (Week 6 Assignments/b0-job.sh) for the b0 mask and extraction. Am I on the right track?

**Comment by kaitlyngreer** [comment]
I was able to identify where the issues were and fix them to have a successful job and batch script. Those as well as the rest of the materials for the assignment have been uploaded under Week 6 Assignments.

**Comment by njhunsak** [comment]
Setting your FSL environmental variables should look something like this:
```
FSLDIR=/fslhome/intj5/apps/fsl-5.0.10/
. ${FSLDIR}/etc/fslconf/fsl.sh
PATH=${FSLDIR}/bin:${PATH}
export FSLDIR PATH
```

**Comment by njhunsak** [comment]
Everything else looks great!
