### ISSUE TITLE
Incorrect values

### ISSUE THREAD

**Issue by njhunsak** [kaitlyngreer/psych516w2020#5]
None of these values are correct. You need to check the JSON files for each participant and determine the correct numbers.

https://github.com/kaitlyngreer/psych516w2020/blob/96d65258cdcbeffbd201d8706f7bbff6833a45f4/Week%207%20Assignments/acqparams.txt#L1

**Comment by kaitlyngreer** [comment]
Adjusted values and have uploaded the adjusted script.
