### ISSUE TITLE
Improvement on pipeline

### ISSUE THREAD

**Issue by njhunsak** [kaitlyngreer/psych516w2020#6]
Just FYI for any future studies, if you are seeing the messy rainbow halo around brains like this, it means you didn't do enough skull stripping on your image. This isn't anything you have to fix now, but it'll be something to address if you ever try to run this as a real study.

![image](https://user-images.githubusercontent.com/4333838/76630144-1df41a00-6505-11ea-9671-d9ff00f3e72f.png)

**Comment by kaitlyngreer** [comment]
For future analyses, would the skull stripping issue need to be addressed in a previous script or is this something that could be run after running the tensor steps?

**Comment by njhunsak** [comment]
It would have to be handled within the previous script.
